spring.application.name=RevPassword_Manager
spring.datasource.url=jdbc:mysql://localhost:3306/RevPassword_Manager_Services?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# JPA/Hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Application
server.port=8080

jwt.secret=h6U9t8Wk2z9P5qR4v7M2L0n3B1X8y5A7V9c4G2f1K6E=
jwt.expiration=86400000